const base = (import.meta.env.VITE_API_URL || 'http://localhost:5001/api').replace(/\/$/, '');
export async function getProjects(category) { const url = new URL(`${base}/projects`); if(category && category !== 'All') url.searchParams.set('category', category); const response = await fetch(url); if(!response.ok) throw new Error('Unable to load projects.'); return (await response.json()).projects; }
function visitorIdentifier() { const existing = localStorage.getItem('impact-visitor'); if (existing) return existing; const created = crypto.randomUUID(); localStorage.setItem('impact-visitor', created); return created; }
export async function getProject(id) { const response = await fetch(`${base}/projects/${id}?visitorIdentifier=${encodeURIComponent(visitorIdentifier())}`); if(!response.ok) throw new Error('Unable to load this project.'); return (await response.json()).project; }
export async function submitRequest(values) { const response = await fetch(`${base}/requests`, {method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(values)}); const result=await response.json(); if(!response.ok) throw new Error(result.message); return result; }
export async function submitContact(values) { const response = await fetch(`${base}/contact`, {method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(values)}); const result=await response.json(); if(!response.ok) throw new Error(result.message); return result; }
export async function getSettings() { const response = await fetch(`${base}/settings`); const result = await response.json(); if (!response.ok) throw new Error(result.message); return result.settings; }
export async function updateSettings(values, accessToken) { const response = await fetch(`${base}/settings`, { method:'PUT', headers:{'Content-Type':'application/json', Authorization:`Bearer ${accessToken}`}, body:JSON.stringify(values) }); const result=await response.json(); if (!response.ok) throw new Error(result.message); return result.settings; }
export async function uploadCompanyLogo(file, accessToken) { const base64 = await new Promise((resolve, reject) => { const reader = new FileReader(); reader.onload = () => resolve(String(reader.result).split(',')[1]); reader.onerror = reject; reader.readAsDataURL(file); }); const response = await fetch(`${base}/settings/logo`, { method:'POST', headers:{'Content-Type':'application/json', Authorization:`Bearer ${accessToken}`}, body:JSON.stringify({ fileName:file.name, mimeType:file.type, base64 }) }); const result=await response.json(); if (!response.ok) throw new Error(result.message); return result.settings; }
export async function likeProject(slug) { const response=await fetch(`${base}/projects/${slug}/like`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({visitorIdentifier:visitorIdentifier()})}); if(!response.ok) throw new Error('Unable to update like.'); return response.json(); }
export async function rateProject(slug,rating) { const response=await fetch(`${base}/projects/${slug}/rating`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({rating,visitorIdentifier:visitorIdentifier()})}); if(!response.ok) throw new Error('Unable to update rating.'); return response.json(); }
export async function submitReview(slug,values) { const response=await fetch(`${base}/projects/${slug}/reviews`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(values)}); const result=await response.json(); if(!response.ok) throw new Error(result.message); return result; }
