import 'dotenv/config';
import express from 'express';
import cors from 'cors';
import helmet from 'helmet';
import morgan from 'morgan';
import { errorHandler } from './middleware/errorHandler.js';
import projectRoutes from './routes/projectRoutes.js';
import publicRoutes from './routes/publicRoutes.js';
import settingsRoutes from './routes/settingsRoutes.js';
const app = express();
const frontendUrl = (process.env.FRONTEND_URL || 'http://localhost:5173').replace(/\/$/, '');
app.use(helmet()); app.use(cors({ origin: frontendUrl })); app.use(express.json({ limit: '1mb' })); app.use(morgan('tiny'));
app.get('/api/health', (req,res) => res.json({ success: true, message: 'Impact Construction API is running' }));
app.use('/api/projects', projectRoutes); app.use('/api/settings', settingsRoutes); app.use('/api', publicRoutes); app.use(errorHandler);
app.listen(Number(process.env.PORT || 5001), () => console.log(`Impact Construction API listening on ${process.env.PORT || 5001}`));
