import { Router } from 'express';
import { supabase } from '../config/supabase.js';
const router = Router();

async function getInteractionStats(projectId, visitorIdentifier) {
  const [likes, ratings, currentLike, currentRating, reviews] = await Promise.all([
    supabase.from('likes').select('id', { count: 'exact', head: true }).eq('project_id', projectId),
    supabase.from('ratings').select('rating').eq('project_id', projectId),
    supabase.from('likes').select('id').eq('project_id', projectId).eq('visitor_identifier', visitorIdentifier).maybeSingle(),
    supabase.from('ratings').select('rating').eq('project_id', projectId).eq('visitor_identifier', visitorIdentifier).maybeSingle(),
    supabase.from('reviews').select('id,name,rating,review,created_at').eq('project_id', projectId).eq('status', 'approved').order('created_at', { ascending: false })
  ]);
  const failed = [likes, ratings, currentLike, currentRating, reviews].find((result) => result.error);
  if (failed) throw failed.error;
  const ratingValues = ratings.data || [];
  return { likesCount: likes.count || 0, ratingsCount: ratingValues.length, averageRating: ratingValues.length ? Number((ratingValues.reduce((sum, item) => sum + item.rating, 0) / ratingValues.length).toFixed(1)) : 0, liked: Boolean(currentLike.data), selectedRating: currentRating.data?.rating || 0, reviews: reviews.data || [] };
}

router.get('/', async (req, res, next) => { try { let query = supabase.from('projects').select('*, project_media(*)').eq('status','published').order('featured',{ascending:false}).order('created_at',{ascending:false}); if(req.query.category && req.query.category !== 'All') query = query.eq('category', req.query.category); const { data, error } = await query; if(error) throw error; res.json({success:true, projects:data}); } catch(error){ next(error); } });
router.get('/:id', async (req, res, next) => { try { const { data, error } = await supabase.from('projects').select('*, project_media(*)').eq('slug', req.params.id).eq('status','published').single(); if(error) throw error; const stats = await getInteractionStats(data.id, req.query.visitorIdentifier || req.ip); res.json({ success: true, project: { ...data, ...stats } }); } catch(error){ next(error); } });
router.post('/:id/like', async (req, res, next) => { try { const { data: project, error: projectError } = await supabase.from('projects').select('id').eq('slug', req.params.id).single(); if(projectError) throw projectError; const visitorIdentifier = req.body.visitorIdentifier || req.ip; const { data: existing, error: findError } = await supabase.from('likes').select('id').eq('project_id', project.id).eq('visitor_identifier', visitorIdentifier).maybeSingle(); if(findError) throw findError; if(existing) { const { error } = await supabase.from('likes').delete().eq('id', existing.id); if(error) throw error; } else { const { error } = await supabase.from('likes').insert({ project_id: project.id, visitor_identifier: visitorIdentifier }); if(error) throw error; } const stats = await getInteractionStats(project.id, visitorIdentifier); res.json({ success: true, ...stats }); } catch(error){ next(error); } });
router.post('/:id/rating', async (req, res, next) => { try { const { data: project, error: projectError } = await supabase.from('projects').select('id').eq('slug', req.params.id).single(); if(projectError) throw projectError; const rating = Number(req.body.rating); if(!Number.isInteger(rating) || rating < 1 || rating > 5) return res.status(400).json({success:false,message:'Rating must be between 1 and 5.'}); const visitorIdentifier = req.body.visitorIdentifier || req.ip; const { data: existing, error: findError } = await supabase.from('ratings').select('id,rating').eq('project_id', project.id).eq('visitor_identifier', visitorIdentifier).maybeSingle(); if(findError) throw findError; if(existing?.rating === rating) { const { error } = await supabase.from('ratings').delete().eq('id', existing.id); if(error) throw error; } else { const { error } = await supabase.from('ratings').upsert({ project_id: project.id, visitor_identifier: visitorIdentifier, rating }, { onConflict:'project_id,visitor_identifier' }); if(error) throw error; } const stats = await getInteractionStats(project.id, visitorIdentifier); res.json({success:true,...stats}); } catch(error){ next(error); } });
router.post('/:id/reviews', async (req,res,next) => { try { const { data: project, error: projectError } = await supabase.from('projects').select('id').eq('slug',req.params.id).single(); if(projectError) throw projectError; const { name, rating, review } = req.body; if(!name || !review || !Number.isInteger(Number(rating)) || Number(rating)<1 || Number(rating)>5) return res.status(400).json({success:false,message:'Name, rating, and a 1-5 star review are required.'}); const { error } = await supabase.from('reviews').insert({ project_id:project.id, name:name.trim(), rating:Number(rating), review:review.trim(), status:'pending' }); if(error) throw error; res.status(201).json({success:true,message:'Review submitted for approval.'}); } catch(error){ next(error); } });
export default router;
